from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home, name='index'),
    path('referral/<str:ref_code>/', views.home, name='index'),
    path('about/', views.about, name='about'),
    path('404/', views.error, name='404'),
    path('blogs/', views.post_list, name='blog'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('tag/<slug:tag_slug>/',
         views.post_list, name='post_list_by_tag'),
    path('services/', views.services, name='services'),
    path('client/register/', views.client_registration, name='client_registration'),
    path('client/login/', views.client_login, name='client_login'),
    path('client/logout/', views.logoutUser, name='client_logout'),
    path('client/list/', views.Client_List, name='Client_list'),
    path('client/checkout_redirect/', views.checkout_redirect, name='client_checkout_redirect'),
    path('create_client/<int:pk_dash>/', views.createclient, name='create_client'),
    path('client/dashboard/<int:pk_dash>/', views.client_dashboard, name='client_dashboard'),
    path('client/pending/<int:pk_dash>/', views.clientPending, name='client_unpaid'),
    path('client/unpaid/order/<int:pk_writerdetails>/', views.client_pending_order_details, name='client_pending_order_details'),
    path('client/paid/order/<int:pk_writerdetails>/', views.client_paid_order_details, name='client_paid_order_details'),
    path('client/assigned/order/<int:pk_writerdetails>/', views.client_assigned_order_details, name='client_assigned_order_details'),
    path('client/delivered/order/<int:pk_writerdetails>/', views.client_delivered_order_details,
         name='client_delivered_order_details'),
    path('client/revision/order/<int:pk_writerdetails>/', views.client_revision_order_details,
         name='client_revision_order_details'),
    path('client/completed/order/<int:pk_writerdetails>/', views.client_completed_order_details,
         name='client_completed_order_details'),
    path('client/cancelled/order/<int:pk_writerdetails>/', views.client_cancelled_order_details,
         name='client_cancelled_order_details'),
    path('client/paid/<int:pk_dash>/', views.clientavailable, name='client_paid'),
    path('client/writerAssigned/<int:pk_dash>/', views.clientAssigned, name='writer_assigned'),
    path('client/revisions/<int:pk_dash>/', views.clientRevisions, name='client_revisions'),
    path('revise/order/<str:order_id>/', views.client_revise_order, name='client_revise_order'),
    path('complete/order/<str:order_id>/', views.client_complete_order, name='client_complete_order'),
    path('cancel/order/<str:order_id>/', views.client_cancel_order, name='client_cancel_order'),
    path('bot/chat/', views.botview, name='bot'),

    path('client/completed/<int:pk_dash>/', views.clientCompleted, name='client_completed'),
    path('client/cancelled/<int:pk_dash>/', views.clientCancelled, name='client_cancelled'),
    path('client/delivered/<int:pk_dash>/', views.clientDelivered, name='writer_delivered'),
    path('complete/order/<str:order_id>/', views.processOrder, name='complete_order_payment'),

    # path('order/details/', views.Order_Details, name='home'),
    path('order/list/', views.Order_List, name='list'),

    path('writer/list/', views.Writer_List, name='Writer_list'),
    path('support/list/', views.Support_List, name='Support_list'),
    path('create_order/<int:pk>/', views.createOrder, name='order'),
    path('admin_order_Create/', views.admincreateOrder, name='admin_order'),
    path('writer/register/', views.writer_registration_view, name='writer_registration'),
    path('writer/login/', views.writer_login, name='writer_login'),
    path('writer/new_writer_login/', views.new_writer_login, name='new_writer_login'),
    path('super/register/', views.superadmincreate, name='createsuperuser'),

    path('writer/logout/', views.logoutwriter, name='writer_logout'),
    path('welcome_back_Kelvin/', views.admin_login, name='admin_login'),
    path('ByebyeKelvin/', views.logoutadmin, name='admin_logout'),

    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="password_reset.html"),
         name="reset_password"),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="password_reset_sent.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="password_reset_form.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="password_reset_done.html"),
         name="password_reset_complete"),

    path('todoform/', views.createTodo, name='create_todo'),
    path('create_writer/', views.createWriter, name='writer'),
    # path('update_order/<str:pk>/', views.updateOrder, name='update_order'),
    path('delete_order/<str:pk>/', views.deleteOrder, name='delete_order'),
    path('order/admin/', views.Order_admin, name='admin'),
    path('writer/dashboard/<int:pk_dash>/', views.Order_List, name='writer_dashboard'),
    path('writer/delivered_orders/<int:pk_dash>/', views.Writer_Orders_Delivered, name='writer_delivered_orders'),
    path('writer/orders/in_progress/kindly_adhere_to_the_deadline/<int:pk_dash>/', views.Writer_Orders_in_progress,
         name='writer_Orders_in_progress'),
    path('writer/revision_orders/<int:pk_dash>/', views.Writer_Orders_Revision, name='writer_revision_orders'),
    path('writer/cancelled_orders/<int:pk_dash>/', views.Writer_Orders_Cancelled, name='writer_cancelled_orders'),
    path('writer/completed_orders/<int:pk_dash>/', views.Writer_completed_orders, name='writer_completed_orders'),
    path('update_profile/<str:pk_dash>/', views.createWriter, name='writer_update_profile'),
    path('writer/order/<int:pk_writerdetails>/', views.Writer_order_details, name='Writer_order_details'),
    path('writer/all_available_orders/<int:pk_dash>/', views.AvailableOrders, name='writer_available_orders'),
    path('writer/profile/<int:pk_dash>/', views.writer_profile, name='writer_profile'),
    path('writer/assigned_order/<int:pk_writerdetails>/', views.Writer_assigned_order_details,
         name='Writer_assigned_order_details'),
    path('writer/delivered_order/<int:pk_writerdetails>/', views.Writer_delivered_order_details,
         name='writer_delivered_order_details'),
    path('writer/revision_order/<int:pk_writerdetails>/', views.Writer_revision_order_details,
         name='writer_revision_order_details'),

    path('writer/available/order/<int:pk_writerdetails>/', views.Writer_available_order_details,
         name='Writer_available_order_details'),
    path('writer/completed_order/<int:pk_writerdetails>/', views.Writer_completed_order_details,
         name='writer_completed_order_details'),
    path('writer/completeOrder/<int:order_id>/', views.writer_complete_order, name='Complete'),
    path('writer/take/<int:order_id>/', views.take_order, name='take'),

    path('order/bidded/', views.adminbidded, name='adminbidded'),
    path('order/unpaid/', views.adminunpaid, name='adminunpaid'),
    path('order/in_progress/', views.admin_progress, name='admin_progress'),
    path('order/delivered/', views.admindelivered, name='admindelivered'),
    path('order/revision/', views.adminrevision, name='adminrevision'),
    path('order/admincancelled/', views.admincancelled, name='admincancelled'),
    path('order/admincompleted/', views.admincompleted, name='admincompleted'),

    path('update_order/<str:pk>/', views.admin_assign_Order, name='update_order'),
    path('revise_order/<str:order_id>/', views.writer_revise_order, name='revise_order'),
    path('checkout/order/<str:order_id>/', views.client_checkout, name='client_checkout'),
    path('complete_order/<str:order_id>/', views.admin_complete_order, name='complete_order'),

    path('rep/dashboard/', views.rep_dashboard, name='rep_dashboard'),
    path('client/<str:pk_profile>/', views.client_profile, name='client'),
    path('support_profile/<str:pk_support>/', views.Support_profile, name='support'),

]