# Generated by Django 3.2.6 on 2021-09-18 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(default=orders.models.Client.random_string, editable=False, max_length=100000000000, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=75, null=True)),
                ('country', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('phone', models.CharField(default='', max_length=15, null=True)),
                ('code', models.CharField(blank=True, max_length=12)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('recommended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ref_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.CharField(default=orders.models.Order.random_string, editable=False, max_length=100000000000, primary_key=True, serialize=False)),
                ('topic', models.CharField(default='Writers Choice', max_length=60)),
                ('service_type', models.CharField(choices=[('6.00', 'Writing From Scratch'), ('0.50', 'Editing And Revision')], default='6.00', max_length=300)),
                ('academic_level', models.CharField(choices=[('1.00', 'High school'), ('2.00', 'College 1'), ('2.50', 'college 2'), ('3.50', 'Masters'), ('4.5', 'Phd')], default='2.00', max_length=300)),
                ('essay_type', models.CharField(choices=[('0.0', 'Essay any type'), ('0.25', 'Admission essay'), ('0.25', 'Annointed bibliography'), ('0.25', 'Article review'), ('0.25', 'Book review'), ('0.25', 'Business plan'), ('0.25', 'Case study'), ('0.25', 'Course work'), ('0.50', 'Creative writing'), ('1.25', 'Critical writing'), ('0.0', 'Presentation'), ('1.0', 'Speech'), ('2.5', 'Research proposal'), ('1.5', 'Research paper'), ('0.75', 'Term paper'), ('3.0', 'Thesis'), ('4.0', 'Dissertation')], default='0.25', max_length=300)),
                ('subject', models.CharField(choices=[('4.00', 'Accounting'), ('1.25', 'African American study'), ('4.00', 'Architecture'), ('1.25', 'Anthropology'), ('1.25', 'Business and entrepreneur'), ('1.25', 'Art theater films'), ('4.00', 'Chemistry'), ('1.25', 'Communication strategies'), ('4.00', 'Computer science'), ('4.00', 'Economics'), ('1.25', 'Education'), ('4.00', 'Engineering'), ('1.25', 'Ethics'), ('1.25', 'Environmental issues'), ('4.00', 'Finance'), ('3.25', 'Geography'), ('1.25', 'Health care'), ('1.25', 'History'), ('1.25', 'International public relationship'), ('5.00', 'Law'), ('1.25', 'Linguistics'), ('1.25', 'Management'), ('1.25', 'Marketing'), ('4.00', 'Mathematics'), ('2.00', 'Music'), ('1.25', 'Nursing'), ('1.25', 'Nutrition'), ('1.25', 'Philosophy'), ('4.00', 'Physics'), ('1.25', 'Political Science'), ('1.25', 'Psychology'), ('1.25', 'Religion And Theology'), ('1.25', 'Sports'), ('1.25', 'Sociology'), ('4.25', 'Technology'), ('1.25', 'Tourism')], default='4.00', max_length=300)),
                ('number_of_pages', models.IntegerField(default='2')),
                ('deadline', models.CharField(choices=[('6.0', '4'), ('5.50', '6'), ('5.25', '8'), ('5.0', '12'), ('4.75', '24'), ('4.50', '48'), ('4.25', '72'), ('4.00', '96'), ('3.75', '120'), ('3.50', '144'), ('3.25', '168')], default='2.00', max_length=300, null=True)),
                ('Paper_Instruction', models.TextField(default='', null=True)),
                ('references', models.CharField(choices=[('Mla', 'Mla'), ('Apa', 'Apa'), ('Harvard', 'Harvard'), ('Chicago', 'Chicago'), ('Other', 'Other')], default='SOME STRING', max_length=300)),
                ('Paper_heading', models.CharField(default='This is the Paper on:', max_length=60, null=True)),
                ('Paperdetails', models.TextField(default='', null=True)),
                ('revision_comment', models.TextField(default='', null=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='')),
                ('number_of_references', models.IntegerField(default='')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Paid', 'Paid'), ('Writer Assigned', 'Writer Assigned'), ('Delivered', 'Delivered'), ('Revision', 'Revision'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending Payment', max_length=300)),
                ('rating', models.CharField(choices=[('0', 'Not Rated'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=1)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Writers',
            fields=[
                ('id', models.CharField(default=orders.models.Writers.random_string, editable=False, max_length=100000000000, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=10)),
                ('second_name', models.CharField(default='', max_length=10)),
                ('pseudonym', models.CharField(default='', max_length=30)),
                ('city', models.CharField(default='', max_length=10)),
                ('phone', models.CharField(default='', max_length=15)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='', null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=300)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('governid', models.FileField(blank=True, null=True, upload_to='')),
                ('university', models.CharField(default='', max_length=10, null=True)),
                ('unidept', models.CharField(default='', max_length=10, null=True)),
                ('diploma', models.FileField(blank=True, null=True, upload_to='')),
                ('statement', models.TextField(default='', null=True)),
                ('writer_quality', models.CharField(choices=[('Beginner Writer', 'Beginner Writer'), ('Advanced Writer', 'Advanced Writer'), ('Expert Writer', 'Expert Writer')], default='Beginner Writer', max_length=300)),
                ('image', models.ImageField(blank=True, default='images/NoImageAvailable.png', null=True, upload_to='images/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writerprof', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=75)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='', max_length=300)),
                ('phone', models.CharField(default='+447584221456', max_length=15)),
                ('statement', models.TextField(default='')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Support', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_posts', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_order', to='orders.order')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('image', models.ImageField(blank=True, default='images/NoImageAvailable.png', height_field='image_height', null=True, upload_to='images/', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(blank=True, default='100', editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, default='100', editable=False, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='support',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.support'),
        ),
        migrations.AddField(
            model_name='order',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.writers'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='orders.post')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
