# Generated by Django 3.2.6 on 2021-09-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_bid_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='spacing',
            field=models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Harvard', 'Harvard'), ('Chicago', 'Chicago'), ('Other', 'Other')], default='SOME STRING', max_length=300),
        ),
    ]
